#!/usr/bin/env bash

: ${IMG_NAME:="nuodb/nuodb:latest"}

docker network create nuodb-net

docker run -d --name ad1 --rm \
    --hostname ad1 \
    --net nuodb-net \
    -p 8888:8888 \
    -p 48004:48004 \
    -p 48005:48005 \
    -e "NUODB_DOMAIN_ENTRYPOINT=ad1" \
    ${IMG_NAME} nuoadmin

COMMAND="docker exec -i ad1 nuocmd show domain"
echo -n "Wating for AP to start..."
while ! $COMMAND 2>/dev/null | grep -q "Connected"; do
    echo -n "."
    sleep 2
done
echo -e "\nAP started!"
echo

# Apply limited license
echo -n "Applying license.. "
docker exec -it -e "NUODB_LIMITED_LICENSE_CONTENT=$NUODB_LIMITED_LICENSE_CONTENT" ad1 /bin/bash -c 'echo "$NUODB_LIMITED_LICENSE_CONTENT" > ~/nuodb.lic && nuocmd set license --license-file ~/nuodb.lic && rm ~/nuodb.lic'
echo "Done!"

#changed to properly create and mount volumes
echo "Starting SM1... "
docker volume create vol1
docker volume create vol2

docker run -d --name sm1 --hostname sm1 --rm \
    --volume vol1:/var/opt/nuodb/backup \
    --volume vol2:/var/opt/nuodb/archive \
    --net nuodb-net ${IMG_NAME} nuodocker \
    --api-server ad1:8888 start sm \
    --db-name test --server-id ad1 \
    --dba-user dba --dba-password dba \
    --labels "zone east node localhost" \
    --archive-dir /var/opt/nuodb/archive
echo "Done!"
echo
echo "Starting TEs... "
docker run -d --name te1 --hostname te1 --rm \
    --net nuodb-net ${IMG_NAME} nuodocker \
    --api-server ad1:8888 start te \
    --db-name test --server-id ad1

docker run -d --name te2 --hostname te2 --rm \
    --net nuodb-net ${IMG_NAME} nuodocker \
    --api-server ad1:8888 start te \
    --db-name test --server-id ad1
echo "Done!"

echo -n "Wating for database to start..."
while ! $COMMAND | grep -q "state = RUNNING"; do
    echo "."
    sleep 2
done
sleep 2
echo "Done!"
$COMMAND

