version: 2.1

jobs:
  smoke_tests:
    docker:
      - image: cimg/node:22.15
    resource_class: 'medium+'
    environment:
      DOCKER_BUILDKIT: 'false'
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Extract NuoDB client from Docker image
          command: bash scripts/fetch-client-from-docker.sh
      - run:
          name: Start NuoDB test database and run tests
          command: make up && make smoke-tests
      - run:
          name: Make sure we clean the test environment
          command: make dn

  nightly_tests:
    docker:
      - image: cimg/node:22.15
    resource_class: 'medium+'
    environment:
      DOCKER_BUILDKIT: 'false'
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Extract NuoDB client from Docker image
          command: bash scripts/fetch-client-from-docker.sh
      - run:
          name: Start NuoDB test database and run tests
          command: make up && make nightly-tests
      - run:
          name: Make sure we clean the test environment
          command: make dn
  coverage_smoke:
    docker:
      - image: cimg/node:22.15
    resource_class: 'medium'
    environment:
      DOCKER_BUILDKIT: 'false'
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Extract NuoDB client from Docker image
          command: bash scripts/fetch-client-from-docker.sh
      - run:
          name: Start NuoDB test database and run tests
          command: |
            make up && \
            make coverage-smoke && \
            scp -r remote-docker:~/project/coverage /tmp/ && \
            ls -las /tmp/coverage
      - run:
          name: Make sure we clean the test environment
          command: make dn
      - store_artifacts:
          path: /tmp/coverage
          destination: coverage-smoke-report
parameters:
  run-nightly-tests:
    type: boolean
    default: false

workflows:
  run_smoke_tests:
    jobs:
      - smoke_tests:
          context:
            - common-config
      - coverage_smoke:
          context:
            - common-config

  run_nightly_tests:
    when:
      when: << pipeline.parameters.run-nightly-tests >>
    jobs:
      - nightly_tests:
          context:
            - common-config
