name: Publish Package to npmjs
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest

    # Uses OIDC Trusted Publishing
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Download and extract NuoDB Client Package
        run: |
            mkdir /tmp/nuodb-client-package
            export NUODB_CLIENT_PACKAGE_URL="$(curl -s https://api.github.com/repos/nuodb/nuodb-client/releases/latest \
            | grep "browser_download_url.*nuodb-client-.*lin-x64.tar.gz" \
            | cut -d : -f 2,3 \
            | tr -d " " | tr -d \")"
            wget -O /tmp/nuodb-client-package/nuodb-client-package.tar.gz -q "$NUODB_CLIENT_PACKAGE_URL"
            cd /tmp/nuodb-client-package && tar xf nuodb-client-package.tar.gz
            mv "/tmp/nuodb-client-package/$(basename "$NUODB_CLIENT_PACKAGE_URL" | sed 's/\.tar\.gz//g')" /tmp/nuodb-client-package/nuodb-client.lin-x64
            echo "NUODB_CLIENT_PACKAGE=/tmp/nuodb-client-package/nuodb-client.lin-x64" >> $GITHUB_ENV
      - run: npm ci
      - run: npm publish

